CREATE TABLE movie_tb
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(250)                            NOT NULL,
    description  text,
    release_date date,
    rating       DOUBLE PRECISION,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_movie_tb PRIMARY KEY (id)
);